In [1]:
# Dependencies
import pandas as pd # allows for comands as pd.function() as opposed to pandas.function()

In [6]:
# We can create a Pandas Series from a raw list
schoollist = ["UCLA", "UC Berkeley", "UC Irvine", "University of Central Florida", "Rutgers University"]

# Converts the python list to a pandas series
dataSeries = pd.Series(schoollist)

dataSeries

0                             UCLA
1                      UC Berkeley
2                        UC Irvine
3    University of Central Florida
4               Rutgers University
dtype: object

In [4]:
# Convert a list of dictionaries into a DataFrame
stateAbbrevs = [
    {"STATE": "New Jersey", "ABBREVIATION": "NJ"},
    {"STATE": "New Jersey", "ABBREVIATION": "NY"}
]
# use pd.DataFrame() to convert this list of dicts to a dataframe
stateDF = pd.DataFrame(stateAbbrevs)

stateDF

        STATE ABBREVIATION
0  New Jersey           NJ
1  New Jersey           NY

In [5]:
# Convert a single dictionary containing lists into a DataFrame
stateAbbrevs = [
    {"STATE": "New Jersey", "ABBREVIATION": "NJ"},
    {"STATE": "New York", "ABBREVIATION": "NY"}
]

# use pd.DataFrame() to convert this list of dicts to a dataframe
stateDF = pd.DataFrame(stateAbbrevs)

stateDF
# dictionary of pharoahs
pharoahsDict = {
    "Dynasty": ["Early Dynastic Period", "Old Kingdom"],
    "Pharoah": ["Thinis", "Memphis"]
}
# dictionary of pharoahs
pharoahsDict = {
    "Dynasty": ["Early Dynastic Period", "Old Kingdom"],
    "Pharoah": ["Thinis", "Memphis"]
}

# use pd.DataFrame to convert the dictionary of lists to a dataframe
pharoahDF = pd.DataFrame(pharoahsDict)

pharoahDF

                 Dynasty  Pharoah
0  Early Dynastic Period   Thinis
1            Old Kingdom  Memphis