In [1]:
# Import Dependencies
import pandas as pd
from pathlib import Path

In [2]:
# Create a path to the csv and read it into a Pandas DataFrame
movieDF = pd.read_csv("resources/movie_scores.csv")
movieDF.head()

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
0,Avengers: Age of Ultron (2015),74,86,66,7.1,7.8,5.0,4.5,3.70,4.3,...,3.90,3.5,4.5,3.5,3.5,4.0,1330,271107,14846,0.5
1,Cinderella (2015),85,80,67,7.5,7.1,5.0,4.5,4.25,4.0,...,3.55,4.5,4.0,3.5,4.0,3.5,249,65709,12640,0.5
2,Ant-Man (2015),80,90,64,8.1,7.8,5.0,4.5,4.00,4.5,...,3.90,4.0,4.5,3.0,4.0,4.0,627,103660,12055,0.5
3,Do You Believe? (2015),18,84,22,4.7,5.4,5.0,4.5,0.90,4.2,...,2.70,1.0,4.0,1.0,2.5,2.5,31,3136,1793,0.5
4,Hot Tub Time Machine 2 (2015),14,28,29,3.4,5.1,3.5,3.0,0.70,1.4,...,2.55,0.5,1.5,1.5,1.5,2.5,88,19560,1021,0.5

In [8]:
# Figure out the minimum and maximum IMDB user vote count
print(f"Maximum IMDB User Votes: {movieDF['IMDB_user_vote_count'].max()}")
print(f"Manimum IMDB User Votes: {movieDF['IMDB_user_vote_count'].min()}")

Maximum IMDB User Votes: 334164
Manimum IMDB User Votes: 243

In [9]:
# Create bins in which to place values based upon IMDB vote count
bins = [0, 2499, 4999, 9999, 14999, 19999, 29999, 49999, 99999, 350000]

# Create labels for these bins
group_labels = ["0 to 2.4k", "2.5k to 4.9k", "5k to 9k", "10k to 14k", "15k to 19k", "20k to 29k",
                "30k to 49k", "50k to 99k", "100k to 350k"]

In [10]:
# Slice the data and place it into bins
pd.cut(movieDF["IMDB_user_vote_count"], bins, labels=group_labels, include_lowest=True)
movieDF.head

<bound method NDFrame.head of                                           FILM  RottenTomatoes  \
0               Avengers: Age of Ultron (2015)              74
1                            Cinderella (2015)              85
2                               Ant-Man (2015)              80
3                       Do You Believe? (2015)              18
4                Hot Tub Time Machine 2 (2015)              14
..                                         ...             ...
141                          Mr. Holmes (2015)              87
142                                 '71 (2015)              97
143                 Two Days, One Night (2014)              97
144  Gett: The Trial of Viviane Amsalem (2015)             100
145         Kumiko, The Treasure Hunter (2015)              87

     RottenTomatoes_User  Metacritic  Metacritic_User  IMDB  Fandango_Stars  \
0                     86          66              7.1   7.8             5.0
1                     80          67              7.5   7.1             5.0
2                     90          64              8.1   7.8             5.0
3                     84          22              4.7   5.4             5.0
4                     28          29              3.4   5.1             3.5
..                   ...         ...              ...   ...             ...
141                   78          67              7.9   7.4             4.0
142                   82          83              7.5   7.2             3.5
143                   78          89              8.8   7.4             3.5
144                   81          90              7.3   7.8             3.5
145                   63          68              6.4   6.7             3.5

     Fandango_Ratingvalue  RT_norm  RT_user_norm  ...  IMDB_norm  \
0                     4.5     3.70          4.30  ...       3.90
1                     4.5     4.25          4.00  ...       3.55
2                     4.5     4.00          4.50  ...       3.90
3                     4.5     0.90          4.20  ...       2.70
4                     3.0     0.70          1.40  ...       2.55
..                    ...      ...           ...  ...        ...
141                   4.0     4.35          3.90  ...       3.70
142                   3.5     4.85          4.10  ...       3.60
143                   3.5     4.85          3.90  ...       3.70
144                   3.5     5.00          4.05  ...       3.90
145                   3.5     4.35          3.15  ...       3.35

     RT_norm_round  RT_user_norm_round  Metacritic_norm_round  \
0              3.5                 4.5                    3.5
1              4.5                 4.0                    3.5
2              4.0                 4.5                    3.0
3              1.0                 4.0                    1.0
4              0.5                 1.5                    1.5
..             ...                 ...                    ...
141            4.5                 4.0                    3.5
142            5.0                 4.0                    4.0
143            5.0                 4.0                    4.5
144            5.0                 4.0                    4.5
145            4.5                 3.0                    3.5

     Metacritic_user_norm_round  IMDB_norm_round  Metacritic_user_vote_count  \
0                           3.5              4.0                        1330
1                           4.0              3.5                         249
2                           4.0              4.0                         627
3                           2.5              2.5                          31
4                           1.5              2.5                          88
..                          ...              ...                         ...
141                         4.0              3.5                          33
142                         4.0              3.5                          60
143                         4.5              3.5                         123
144                         3.5              4.0                          19
145                         3.0              3.5                          19

     IMDB_user_vote_count  Fandango_votes  Fandango_Difference
0                  271107           14846                  0.5
1                   65709           12640                  0.5
2                  103660           12055                  0.5
3                    3136            1793                  0.5
4                   19560            1021                  0.5
..                    ...             ...                  ...
141                  7367            1348                  0.0
142                 24116             192                  0.0
143                 24345             118                  0.0
144                  1955              59                  0.0
145                  5289              41                  0.0

[146 rows x 22 columns]>

In [11]:
# Place the data series into a new column inside of the DataFrame
movieDF["IMDB User Votes Group"] = pd.cut(movieDF["IMDB_user_vote_count"], bins, labels=group_labels, include_lowest=True)
movieDF.head()

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference,IMDB User Votes Group
0,Avengers: Age of Ultron (2015),74,86,66,7.1,7.8,5.0,4.5,3.70,4.3,...,3.5,4.5,3.5,3.5,4.0,1330,271107,14846,0.5,100k to 350k
1,Cinderella (2015),85,80,67,7.5,7.1,5.0,4.5,4.25,4.0,...,4.5,4.0,3.5,4.0,3.5,249,65709,12640,0.5,50k to 99k
2,Ant-Man (2015),80,90,64,8.1,7.8,5.0,4.5,4.00,4.5,...,4.0,4.5,3.0,4.0,4.0,627,103660,12055,0.5,100k to 350k
3,Do You Believe? (2015),18,84,22,4.7,5.4,5.0,4.5,0.90,4.2,...,1.0,4.0,1.0,2.5,2.5,31,3136,1793,0.5,2.5k to 4.9k
4,Hot Tub Time Machine 2 (2015),14,28,29,3.4,5.1,3.5,3.0,0.70,1.4,...,0.5,1.5,1.5,1.5,2.5,88,19560,1021,0.5,15k to 19k

In [13]:
# Create a GroupBy object based upon "IMDB User Votes Group"
imdbGroups = movieDF.groupby("IMDB User Votes Group")

# Find how many rows fall into each bin
print(imdbGroups["FILM"].count())

# Get the average of each of the first 5 rating columns within the GroupBy object
imdbGorups[["ROttenTOmatoes", "RottenTomatoes_Users", "Metacritic", "Metacritic_User", "IMDB"]].mean()

IMDB User Votes Group
0 to 2.4k       18
2.5k to 4.9k    12
5k to 9k        16
10k to 14k      15
15k to 19k      18
20k to 29k      16
30k to 49k      19
50k to 99k      16
100k to 350k    16
Name: FILM, dtype: int64

C:\Users\nolan\AppData\Local\Temp\ipykernel_97572\382387958.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  imdbGroups = movieDF.groupby("IMDB User Votes Group")

NameError: name 'imdbGorups' is not defined